CONFIG = {
    "label": "mads_fontan_sr",
    "algorithm_label": "mads_fontan_sr",
    "max_evals": 40,
    "geometry_penalty": 1.0e9,
    "space": {
        "names": (
            "bump1_amp",
            "bump2_amp",
            "size_scale",
            "straighten_strength",
            "offset_x",
        ),
        "x0": [0.0, 0.0, 1.0, 0.0, 0.0],
        "lower": [0.0, 0.0, 0.8, 0.0, -2.7],
        "upper": [0.45, 4.5, 1.0, 0.4, 0.0],
    },
    "optimizer": {
        "type": "mads",
        "n_workers": 8,
        "parallel": True,
        "cache_round": None,
        "subprocess": True,
        "print_bounds": True,
    },
    "objective": {
        # pitch = Z_EXTENT / z_voxels
        "vef_config_path": "configs/vef/vef_fontan_sr_mads_opt.json",
        "output_root": "data/vef_fontan_opt/vef_outputs",
        "runs_root": "data/vef_fontan_opt/runs",
        "z_voxels": 250,
        "sim_resolution": 250,
        "keep_temp_files": False,
        "maximize": False,
    },
    "solver": {
        "binary_name": "sim_fontan_sr",
        # "binary_path": "submodules/tnl-lbm/build/sim_NSE/sim_fontan_sr",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 4,
            "mem": "8G",
            "walltime": "22:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "submit": {
        "job_name": "mads-opt-fontan",
        "time": "168:00:00",
        "cpus": 8,
        "gpus": None,
        "mem": "16G",
        "partition": None,
        "output": "opt-fontan-mads-%j.out",
        "open_mode": "append",
    },
}
