CONFIG = {
    "label": "nm_fontan_tke_2",
    "algorithm_label": "nm_fontan_tke_2",
    "max_evals": 100,
    "geometry_penalty": 1.0e9,
    "space": {
        "names": (
            "bump1_amp",
            "bump2_amp",
            "size_scale",
            "straighten_strength",
            "offset_x",
        ),
        "x0": [0.0, 0.0, 1.0, 0.04, 0.0],
        "lower": [0.0, 0.0, 0.8, 0.0, -2.7],
        "upper": [0.45, 4.5, 1.0, 0.4, 0.0],
    },
    "optimizer": {
        "type": "nelder_mead",
        "n_workers": 6,
        "parallel": True,
        "force_thread_pool": False,
        "memoize": True,
        "parallel_poll_points": True,
        "log_simplex": True,
        "step": [0.1, 0.1, -0.1, 0.1, -0.1],
        "no_improve_thr": 1.0e-3,
        "no_improv_break": 10,
        "penalty": 1.0e9,
        "tol": 1.0e-3,
        "print_bounds": True,
        "initial_simplex": [
            [0.0, 0.0, 1.0, 0.04, 0.0],
            [0.045, 0.0, 1.0, 0.0, 0.0],
            [0.0, 0.45, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0, -0.27],
            [0.0, 0.0, 0.98, 0.0, 0.0],
        ],
        "initial_simplex_values": [
            1.05706e-06,
            1.11905e-06,
            1.30768e-06,
            1.40289e-06,
            1.5747e-06,
            1.67737e-06,
        ],
    },
    "objective": {
        # pitch = Z_EXTENT / z_voxels
        "vef_config_path": "configs/vef/vef_fontan_tke_opt.json",
        "output_root": "data/vef_fontan_opt/vef_outputs",
        "runs_root": "data/vef_fontan_opt/runs",
        "z_voxels": 300,
        "sim_resolution": 300,
        "keep_temp_files": False,
        "maximize": False,
    },
    "solver": {
        "binary_name": "sim_fontan_tke",
        # "binary_path": "submodules/tnl-lbm/build/sim_NSE/sim_fontan_tke",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 4,
            "mem": "8G",
            "walltime": "22:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "submit": {
        "job_name": "nm-opt-fontan-tke",
        "time": "168:00:00",
        "cpus": 8,
        "gpus": None,
        "mem": "16G",
        "partition": None,
        "output": "opt-fontan-tke-nm-%j.out",
        "open_mode": "append",
    },
}
