CONFIG = {
    "label": "nm_tcpc_resume",
    "algorithm_label": "nelder_mead_resume",
    "objective_kind": "tcpc",
    "resolution": 4,
    "max_evals": 50,
    "geometry_penalty": 1.0e9,
    "space": {
        "names": ("offset", "lower_angle", "upper_angle", "lower_flare", "upper_flare"),
        "x0": [-0.00392024, -2.60526, 6.34250, 0.00178604, 0.00135284],
        "lower": [-0.010, -10.0, -5.0, 0.0010, 0.0005],
        "upper": [0.006, 13.0, 15.0, 0.0025, 0.0025],
    },
    "optimizer": {
        "type": "nelder_mead",
        "n_workers": 8,
        "parallel": True,
        "force_thread_pool": False,
        "memoize": True,
        "parallel_poll_points": True,
        "log_simplex": True,
        "no_improve_thr": 1.0e-3,
        "no_improv_break": 10,
        "penalty": 1.0e9,
        "tol": 1.0e-3,
        "simplex_npz_env": "TCPC_NM_SIMPLEX_NPZ",
    },
    "solver": {
        "binary_name": "sim_tcpc_2",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 8,
            "mem": "32G",
            "walltime": "20:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "split": {
        "time_index": -1,
        "min_fraction": 0.25,
        "write_vtp": False,
        "write_debug_points": False,
    },
    "submit": {
        "job_name": "nm-opt-tcpc-resume",
        "time": "168:00:00",
        "cpus": 8,
        "gpus": 1,
        "mem": "32G",
        "output": "opt-tcpc-nm-resume-%j.out",
        "open_mode": "append",
    },
}
