CONFIG = {
    "label": "nm_tcpc",
    "algorithm_label": "nelder_mead",
    "objective_kind": "tcpc",
    "resolution": 4,
    "max_evals": 50,
    "geometry_penalty": 1.0e9,
    "space": {
        "names": ("offset", "lower_angle", "upper_angle", "lower_flare", "upper_flare"),
        "x0": [0.001, 4.0, -3.0, 0.001, 0.001],
        "lower": [-0.01, -15.0, -15.0, 0.0, 0.0],
        "upper": [0.01, 15.0, 15.0, 0.0025, 0.0025],
    },
    "optimizer": {
        "type": "nelder_mead",
        "n_workers": 8,
        "parallel": True,
        "force_thread_pool": False,
        "memoize": True,
        "parallel_poll_points": True,
        "log_simplex": False,
    },
    "solver": {
        "binary_name": "sim_tcpc_2",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 8,
            "mem": "16G",
            "walltime": "20:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "split": {
        "time_index": -1,
        "min_fraction": 0.25,
        "write_vtp": False,
        "write_debug_points": False,
    },
    "submit": {
        "job_name": "nm-opt-tcpc",
        "time": "168:00:00",
        "cpus": 8,
        "gpus": 1,
        "mem": "32G",
        "output": "opt-tcpc-nm-%j.out",
        "open_mode": "append",
    },
    "extra_points": {
        "csv_default": "tmp/extra_points/extra_points_objectives.csv",
        "algorithm_label": "extra_points",
        "submit": {
            "job_name": "tcpc-extra-point",
            "time": "48:00:00",
            "cpus": 4,
            "gpus": None,
            "mem": "16G",
            "output": "tcpc-extra-%j.out",
            "open_mode": "append",
        },
    },
}
