CONFIG = {
    "label": "nm_tcpc_tke_resume2",
    "algorithm_label": "nelder_mead_tke_resume2",
    "objective_kind": "tke",
    "resolution": 5,
    "max_evals": 30,
    "geometry_penalty": 1.0e9,
    "eval_log_shared_path": "data/junction_tcpc_logs/shared/nelder_mead_tke_resume2.csv",
    "space": {
        "names": ("offset", "lower_angle", "upper_angle", "lower_flare", "upper_flare"),
        "x0": [-2.2e-3, -1.4, -5.4, 2.475e-3, 9.50e-4],
        "lower": [-4.2e-3, -4.4, -8.4, 2.225e-3, 7.0e-4],
        "upper": [-2.0e-4, 1.6, -2.4, 2.5e-3, 1.2e-3],
    },
    "optimizer": {
        "type": "nelder_mead",
        "n_workers": 4,
        "parallel": True,
        "force_thread_pool": True,
        "memoize": True,
        "parallel_poll_points": True,
        "log_simplex": True,
        "no_improve_thr": 1.0e-3,
        "no_improv_break": 10,
        "penalty": 1.0e9,
        "tol": 1.0e-3,
        "print_bounds": True,
    },
    "solver": {
        "binary_name": "sim_tcpc_tke",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 8,
            "mem": "16G",
            "walltime": "22:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "split": {
        "time_index": -1,
        "min_fraction": 0.25,
        "write_vtp": False,
        "write_debug_points": False,
    },
    "submit": {
        "job_name": "nm-opt-tcpc-tke-resume2",
        "time": "168:00:00",
        "cpus": 4,
        "gpus": None,
        "mem": "16G",
        "output": "opt-tcpc-tke-nm-resume2-%j.out",
        "open_mode": "append",
    },
}
