CONFIG = {
    "label": "nm_tcpc_tke_resume3",
    "algorithm_label": "nelder_mead_tke_resume3",
    "objective_kind": "tke",
    "resolution": 5,
    "max_evals": 30,
    "geometry_penalty": 1.0e9,
    "eval_log_shared_path": "data/junction_tcpc_logs/shared/nelder_mead_tke_resume3.csv",
    "space": {
        "names": ("offset", "lower_angle", "upper_angle", "lower_flare", "upper_flare"),
        "x0": [-0.0006200056, 4.0741258864, -0.867244527200001, 0.0022396408, 0.0006426583999999],
        "lower": [-0.0012, 3.9, -1.6, 0.0019, 0.00055],
        "upper": [0.0002, 5.3, 0.5, 0.0025, 0.00085],
    },
    "optimizer": {
        "type": "nelder_mead",
        "n_workers": 4,
        "parallel": True,
        "force_thread_pool": False,
        "memoize": True,
        "parallel_poll_points": True,
        "log_simplex": True,
        "no_improve_thr": 1.0e-3,
        "no_improv_break": 10,
        "penalty": 1.0e9,
        "tol": 1.0e-3,
        "print_bounds": True,
    },
    "solver": {
        "binary_name": "sim_tcpc_tke",
        "slurm": {
            "partition": None,
            "gpus": 1,
            "cpus": 8,
            "mem": "16G",
            "walltime": "22:00:00",
            "poll_interval": 60.0,
            "avg_window": 1.0,
            "verbose": False,
        },
    },
    "split": {
        "time_index": -1,
        "min_fraction": 0.25,
        "write_vtp": False,
        "write_debug_points": False,
    },
    "submit": {
        "job_name": "nm-opt-tcpc-tke-resume3",
        "time": "168:00:00",
        "cpus": 4,
        "gpus": None,
        "mem": "16G",
        "output": "opt-tcpc-tke-nm-resume3-%j.out",
        "open_mode": "append",
    },
}
